Add stats command
StreetOfCode/discord-bot pull request #30
Opened 2021-07-06 15:57 UTC by xjahic

If you want to test it yourself be sure to add these to .env:
```
MAX_OLD_STAT_GRAPH_IN_DAYS =
BOT_COMMANDS_CHANNEL_ID =
```
Also you should import data (user_survey_answer) to your localhost db so you won't end up with empty statistics
However I am more than happy to show you how it works

2021-07-06 18:00 UTC, gabrielKerekes requested changes
This is it for today. I got a little bit carried away, sorry 😄  I haven't yet tried to run it, I'll do that later.

2021-07-11 10:10 UTC, xjahic commented on src/cogs/public_commands.py
> +    @commands.command(name="stats")
Renamed to `show-stats`

2021-07-11 10:28 UTC, xjahic commented on src/stats/stats.py
> +def get_options_and_answers(survey_question_id):
Ok

2021-07-11 11:01 UTC, xjahic commented on src/stats/stats.py
> +    data = pd.DataFrame({"Option": options, "Answers": answers})
Good point, I removed it. Now it is just dictionary

2021-07-11 11:05 UTC, xjahic commented
I made a fixup 1af184c7406638446305244d98c9001af2057b0c with almost all requested changes

2021-07-12 17:22 UTC, gabrielKerekes commented
Looks good now! Awesome job! Please squash and merge! 🥳 🎈

2021-07-13 16:20 UTC, merged