Add deployment docs
StreetOfCode/discord-bot pull request #38
Opened 2021-11-09 21:15 UTC by gabrielKerekes

2021-11-10 07:00 UTC, xjahic requested changes
Nice. I would add just a small details as commented.

2021-11-10 07:00 UTC, xjahic commented on docs/DEPLOYMENT.md
> +10. Push `master` to Heroku
Maybe I would add that: "Open second terminal (keep one with the logs) and push 'master' to Heroku."

2021-11-10 07:00 UTC, xjahic commented on docs/DEPLOYMENT.md
> +6. Run yoyo migrations
I would add - "After this command carefully check logs if everything went ok. Also connect to DB if you can and check if DB tables were updated as you wanted them"

2021-11-10 07:00 UTC, xjahic commented on docs/DEPLOYMENT.md
> +5. Change `yoyo-local.ini` `database` to the `DATABASE_URL` from Heroku
I would add: "If migrations weren't changed, you can skip step 5 and step 6."

2021-11-25 18:14 UTC, gabrielKerekes commented
Thanks! Your suggestions should be applied. In addition I also changed all the steps to end with a `.` 🤷

2021-11-25 19:40 UTC, merged